server:
 port: 8761 # 你的端口
spring:
#  security:
#    user:
#      name: admin
#      password: admin
  application:
    name: sba-eureka-client
eureka:
 instance:
   hostname: localhost # 你的地址
   instance-id: ${spring.application.name}:${server.port}:@project.version@
   prefer-ip-address: true
 client:
   registerWithEureka: false # 表示是否注册自身到eureka服务器，因为当前这个应用就是eureka服务器，没必要注册自身，所以这里是false
   fetchRegistry: false # fetchRegistry表示是否从eureka服务器获取注册信息
   serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/